version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: golangAPI
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    secrets:
      - mongo_secrets
    networks:
      - api-network


  cache:
    image: redis:7.2.1
    container_name: cache
    ports:
      - 6379:6379
    volumes:
      - mongodb_data_container:/data
    networks:
      - api-network

  app:
    build: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - cache
      - mongodb_container
    networks:
      - api-network
    
secrets:
  mongo_secrets:
    file: ./secrets.txt

volumes:
  mongodb_data_container:

networks:
  api-network:
    driver: bridge